version: '2'
services:
    web:
        container_name: flaconi_web
        image: flaconi/nginx
        build:
            context: ./containers/nginx/
            dockerfile: Dockerfile
        env_file:
            - ".env"
        volumes:
            - "../application:/var/www/html"
            - "./config/etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
        networks:
            default:
                ipv4_address: 192.100.10.20
        extra_hosts:
            - "flaconi.develop:192.100.10.20"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - php
            - mysqldb

    php:
        container_name: flaconi_php
        image: flaconi/php
        build:
            context: ./containers/php/
            dockerfile: Dockerfile
        env_file:
            - ".env"
        restart: always
        extra_hosts:
            - "flaconi.develop:192.100.10.20"
        volumes:
            - "./config/etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "../application:/var/www/html"

    application:
        container_name: flaconi_application
        image: flaconi/application
        build:
            context: ./containers/application/
            dockerfile: Dockerfile
        volumes:
            - "../application:/var/www/html"
        command:
            - folders.sh
        depends_on:
            - php
            - web
            - composer

    composer:
        container_name: flaconi_composer
        image: "composer"
        env_file:
            - ".env"
        volumes:
            - "../application:/app"
        command: install

    myadmin:
        container_name: flaconi_myadmin
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8080:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${MYSQL_HOST}
        restart: always
        depends_on:
            - mysqldb

    mysqldb:
        container_name: flaconi_mysql
        image: mysql
        container_name: ${MYSQL_HOST}
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "8989:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
            - "./config/db/flaconi.sql:/docker-entrypoint-initdb.d/flaconi.sql:ro"

networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
                -
                    subnet: 192.100.10.0/24
                    gateway: 192.100.10.1
